travis:
  secure:
    BINSTAR_TOKEN: iV741V5wmbz9+8apexrVpYhTYznTIyWlLerwLxbHyadpVtkVMur9yUPDMYM1u1AHvMvaFIl8ZhRsCKQGqbb/lMtB3wpQX7dI2oFdpOX0S+sNH2KI5uAAhOIuUczEhfcAQ+DS0FJPlBWv/RkcLMU6eWAw225l2ZDQmWGy2jgx2RpqhyvcRq5CpYZ5ET2/aKwDshgtTFcUSwZkWApRqWi4dVfn8/MMfXkZo0BzERXCg27C1dfdw/u9zleYqlMW/rJHQ2mk0RqN6467+DdtoyDlRr79kmrvlpf4wsqAMIOjREPe16dq4hNUzZE9qK3pnFcF4pbbEEVtbKltaH1d/5DvxjIUbBXQP19nWRbOVGVl+MQaMa5xS6fDOV9vChmuva0HAOclP3aYoA9HhGj+Pnm2PApophB1aGuiBvMi/xSTyDeha17phx7r23iEeyXwyW614vobGaiVcfC2g0KgzifoOBBbRdkcVw9Dj1JxySY0mOtYtcJcNfLq7Vs/UpQ12m9MupmVb6zWCW9uiV3CuppWqUu9iI0wBmMUe7eH8HkXEM5RKcVArDF6VfYim/rxWVg/OgvEca54Vkkc02sMdOL7+9zGSGgPuK52L7edUy5yQvNdk0dfXChVAME4ERZQM10OhB451EpT3Kxvqj++XYVu0nxr2Yy6/bsij+VW+aa4tgc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
