travis:
  secure:
    BINSTAR_TOKEN: JEH3Bn1rJFTZ9fjtAdIWHb/0BBJmDDpGGB4P3LISA6rfXivyrwmignJo83AZX6P2TmNYtKKoULruqBcDeZrGrf8ANPUdP45K+yULkolAUK7RPA4aGexy9JOknBp3X5ByExFcJge6XW9Yb6eu4Qr7g4NC8fcBhjgKKGq5uqpuUxZy0A3u0SAOgQdtOe2hwX0wQTLZYHIf24t9I32TiGH2MzYPcRc2SBOWnjX8QDK6Sih7A3+UJeDlT6miVaXI9FODzXOsYfMW8jmT2IiRvEwkVge6kA8cdA6LzMNSyX8w2M1abN+tM7iDPPSqtzkouEqq47sgWeLB3od4VrnoFJeuuVkrSCV9yYXwvn5IA4dfib+nxFEZ/8OvPADb1NnhnG3gm7GBRnURn1joz9Bj7HbLY8Tk/AwzgwgZWIQTERExXONpVwvTcSH7phTKmcpgA1KrtahSYHfUDZzGq0sZT9NtNI+dVOLxfe0xQD1mbKI/R6A2EEgoAdfXurTyseX5PFnE24cb/n5HzsWsq9iqp9INfyhYH2LSJ4m2VRbTGqpGbY5Xrp6RBfi11QsxdAv3pbNJp6cPX0023Hw/hnhdIjqI4hwtC+8pMKzAk5VOF8JiWkvX0+ZyFDwBmIvZrPRBMHPeq8MZqIcKbf+PCPGcgf4+ZO4nmc5xeggR+ZDVgBt/GTA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
