travis:
  secure:
    BINSTAR_TOKEN: BLZWU9Bvo526bu+gPWhYblzAopID9uvNACHeScoDIfHwYx5DSgOoLxvx/MhIFN5POxJJNDUo7OkkNnLHVVAEkxBS52V5tgSsvCuDLwLFYhuGrBVIFKx1Ra+rKvfiP05PBJNxvp4NxO2SbBAmBsAaQlXSRNlHM694RKDBwIfMzt8FY0JJicxvLxpW2Dw/Cfwl9KpqDrYYCOWnQve4ZW4ehoIcbjxkUw1fC2iaGNC8RC+aHkIzKn0NRBLwZ8Ato8JoumINAr8mFiUOwAq5r+bpQtfOxOYo+qcNs3unBStuT5ax771q6T49EwCQAvCOTKL93EBtGSI3s+eiHpy1FARfSDZxX1VrNnJCOF+LDrMG3pk9rImT4D0QqEIVPFozQotfymza8T9uSmPXfOZZSSR3Ckp3h3fD1Z+sxLJJ7su9RPMet/5Y3v5A6tM4bR+D6KarEV/OcVtPrTi1tOuD5zjW1WyUMW0kZUlIbWlMc7+jxxMJ0QNRai8xRma+eNsTVaHPFcje8q3lpDukjmvICp+lr48kSecU1WkEwtwBTt+Dllz2FLtJNcQ2uDRq8QD+kpaYgO3LF//YK/YsMhJUIaXJNNa+RzwC87s80nRqU1NASUTHVolRKXh2y+lUmkdSM/FBmnHexziG0dlheIsgmC8JoFwCcCaJi/rU3IiZV0QXUCM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
